version: '2'
services:
  wdyw_db:
    container_name: "wdyw_db"
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
#    command: client --default-character-set=utf8
#    command: mysqld --character-set-results=utf8
#    command: mysqld --character-set-client=utf8
#    command: mysqld --character-set-connection=utf8
#--init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=wdyw_db
      - MYSQL_USER=wdyw
      - MYSQL_PASSWORD=wdyw
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 4162:3306

  wdyw_db_r:
    container_name: "wdyw_db_r"
    image: mysql:latest
    environment:
        - MYSQL_DATABASE=wdyw_db_r
        - MYSQL_USER=wdyw
        - MYSQL_PASSWORD=wdyw
        - MYSQL_ROOT_PASSWORD=root
    ports:
        - 4163:3306

  jjdz4-webapp:
    container_name: "jjdz4-webapp"
    build: .
    environment:
      - MYSQL_URI=wdyw_db:3306
      - MYSQL_DATABASE=wdyw_db
      - MYSQL_USER=wdyw
      - MYSQL_PASSWORD=wdyw
      - DATASOURCE_NAME=java:/WDYWDs
      - MYSQL_R_URI=wdyw_db_r:3306
      - MYSQL_R_DATABASE=wdyw_db_r
      - MYSQL_R_USER=wdyw
      - MYSQL_R_PASSWORD=wdyw
      - DATASOURCE_R_NAME=java:/WDYWreportsDS
    ports:
      - 4160:8080
      - 4161:9990
    depends_on:
      - wdyw_db
      - wdyw_db_r