USE wdyw_db;

ALTER DATABASE `wdyw_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `Category` CONVERT TO CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `Category` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `Answer` CONVERT TO CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `Answer` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `Question` CONVERT TO CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `Question` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `users` CONVERT TO CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `users` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `roles` CONVERT TO CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `roles` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;